PACKAGE_NAME="gc555"
PACKAGE_VERSION="@PACKAGE_VERSION@"
AUTOINSTALL="yes"

MAKE[0]="make KDIR=/usr/lib/modules/$kernelver/build"

BUILT_MODULE_NAME[0]="gc555"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/pci/gc555"
